import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import BackgroundAnimation from "./_components/BackgroundAnimation";
import Header from "./_components/Header";
import StatsSection from "./_components/StatsSection";
import ArchitectureSection from "./_components/ArchitectureSection";
import CtaSection from "./_components/CtaSection";
import TrustSection from "./_components/TrustSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className="relative min-h-screen">
          <BackgroundAnimation />
          <main className="bg-transparent antialiased overflow-hidden font-geist relative z-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
